// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sh8lny.Persistence.Contexts;

#nullable disable

namespace Sh8lny.Persistence.Migrations
{
    [DbContext(typeof(Sha8lnyDbContext))]
    [Migration("20251117061800_AddProjectModules")]
    partial class AddProjectModules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sh8lny.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int?>("RelatedEntityID")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("ActivityType")
                        .HasDatabaseName("IDX_ActivityLog_ActivityType");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IDX_ActivityLog_CreatedAt");

                    b.HasIndex("UserID")
                        .HasDatabaseName("IDX_ActivityLog_UserID");

                    b.HasIndex("RelatedEntityType", "RelatedEntityID")
                        .HasDatabaseName("IDX_ActivityLog_RelatedEntity");

                    b.ToTable("ActivityLog", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Application", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CoverLetter")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PortfolioURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("ProposalDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Submit");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ApplicationID");

                    b.HasIndex("AppliedAt")
                        .HasDatabaseName("IDX_Applications_AppliedAt");

                    b.HasIndex("ProjectID")
                        .HasDatabaseName("IDX_Applications_ProjectID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_Applications_Status");

                    b.HasIndex("StudentID")
                        .HasDatabaseName("IDX_Applications_StudentID");

                    b.HasIndex("ProjectID", "StudentID")
                        .IsUnique()
                        .HasDatabaseName("UQ_Application_ProjectID_StudentID");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Certificate", b =>
                {
                    b.Property<int>("CertificateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateID"));

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CertificateTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CertificateURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("CertificateID");

                    b.HasIndex("CertificateNumber")
                        .IsUnique()
                        .HasDatabaseName("IDX_Certificates_CertificateNumber");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("IDX_Certificates_CompanyID");

                    b.HasIndex("ProjectID")
                        .HasDatabaseName("IDX_Certificates_ProjectID");

                    b.HasIndex("StudentID")
                        .HasDatabaseName("IDX_Certificates_StudentID");

                    b.ToTable("Certificates", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyLogo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CompanyID");

                    b.HasIndex("AverageRating")
                        .HasDatabaseName("IDX_Companies_AverageRating");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasDatabaseName("IDX_Companies_UserID");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.CompanyReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<decimal?>("CommunicationRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompanyRespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("CompensationRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("CompletedOpportunityID")
                        .HasColumnType("int");

                    b.Property<string>("Cons")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsAnonymous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("LearningOpportunityRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("MentorshipRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Pros")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ReviewTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("WorkEnvironmentRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<bool>("WouldRecommend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("ReviewID");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("IDX_CompanyReviews_CompanyID");

                    b.HasIndex("CompletedOpportunityID")
                        .IsUnique()
                        .HasDatabaseName("IDX_CompanyReviews_CompletedOpportunityID")
                        .HasFilter("[CompletedOpportunityID] IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IDX_CompanyReviews_CreatedAt");

                    b.HasIndex("Rating")
                        .HasDatabaseName("IDX_CompanyReviews_Rating");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_CompanyReviews_Status");

                    b.HasIndex("StudentID")
                        .HasDatabaseName("IDX_CompanyReviews_StudentID");

                    b.HasIndex("StudentID", "CompletedOpportunityID")
                        .IsUnique()
                        .HasDatabaseName("UQ_CompanyReviews_StudentID_CompletedOpportunityID")
                        .HasFilter("[CompletedOpportunityID] IS NOT NULL");

                    b.ToTable("CompanyReviews", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.CompletedOpportunity", b =>
                {
                    b.Property<int>("CompletedOpportunityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompletedOpportunityID"));

                    b.Property<string>("Achievements")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int?>("CertificateID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyFeedback")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVisibleOnProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OpportunityTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OpportunityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("SkillsGained")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StudentFeedback")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("CompletedOpportunityID");

                    b.HasIndex("ApplicationID")
                        .IsUnique()
                        .HasDatabaseName("IDX_CompletedOpportunities_ApplicationID")
                        .HasFilter("[ApplicationID] IS NOT NULL");

                    b.HasIndex("CertificateID")
                        .IsUnique()
                        .HasDatabaseName("IDX_CompletedOpportunities_CertificateID")
                        .HasFilter("[CertificateID] IS NOT NULL");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("IDX_CompletedOpportunities_CompletedAt");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("IDX_CompletedOpportunities_IsVerified");

                    b.HasIndex("OpportunityType")
                        .HasDatabaseName("IDX_CompletedOpportunities_OpportunityType");

                    b.HasIndex("ProjectID")
                        .HasDatabaseName("IDX_CompletedOpportunities_ProjectID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_CompletedOpportunities_Status");

                    b.HasIndex("StudentID")
                        .HasDatabaseName("IDX_CompletedOpportunities_StudentID");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("CompletedOpportunities", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationID"));

                    b.Property<string>("ConversationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConversationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("ConversationID");

                    b.HasIndex("ConversationType")
                        .HasDatabaseName("IDX_Conversations_ConversationType");

                    b.HasIndex("GroupID")
                        .HasDatabaseName("IDX_Conversations_GroupID");

                    b.HasIndex("LastMessageAt")
                        .HasDatabaseName("IDX_Conversations_LastMessageAt");

                    b.HasIndex("ProjectID");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.ConversationParticipant", b =>
                {
                    b.Property<int>("ParticipantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantID"));

                    b.Property<int>("ConversationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ParticipantID");

                    b.HasIndex("ConversationID")
                        .HasDatabaseName("IDX_ConversationParticipants_ConversationID");

                    b.HasIndex("UserID")
                        .HasDatabaseName("IDX_ConversationParticipants_UserID");

                    b.HasIndex("ConversationID", "UserID")
                        .IsUnique()
                        .HasDatabaseName("IDX_ConversationParticipants_ConversationID_UserID");

                    b.ToTable("ConversationParticipants", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.DashboardMetric", b =>
                {
                    b.Property<int>("MetricID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetricID"));

                    b.Property<decimal>("ActivityIncreasePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("AvailableOpportunities")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("CompletedProjects")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("MetricDate")
                        .HasColumnType("date");

                    b.Property<int>("NewApplicants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalProjects")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UniversityID")
                        .HasColumnType("int");

                    b.HasKey("MetricID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("MetricDate")
                        .HasDatabaseName("IDX_DashboardMetrics_MetricDate");

                    b.HasIndex("UniversityID");

                    b.ToTable("DashboardMetrics", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("UniversityID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IDX_Departments_IsActive");

                    b.HasIndex("UniversityID")
                        .HasDatabaseName("IDX_Departments_UniversityID");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupMemberID"));

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("GroupMemberID");

                    b.HasIndex("GroupID")
                        .HasDatabaseName("IDX_GroupMembers_GroupID");

                    b.HasIndex("StudentID")
                        .HasDatabaseName("IDX_GroupMembers_StudentID");

                    b.HasIndex("GroupID", "StudentID")
                        .IsUnique()
                        .HasDatabaseName("IDX_GroupMembers_GroupID_StudentID");

                    b.ToTable("GroupMembers", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<string>("AttachmentName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AttachmentURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ConversationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Text");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MessageID");

                    b.HasIndex("ConversationID")
                        .HasDatabaseName("IDX_Messages_ConversationID");

                    b.HasIndex("IsRead")
                        .HasDatabaseName("IDX_Messages_IsRead");

                    b.HasIndex("SenderID")
                        .HasDatabaseName("IDX_Messages_SenderID");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IDX_Messages_SentAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("ActionURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RelatedApplicationID")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedProjectID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IDX_Notifications_CreatedAt");

                    b.HasIndex("IsRead")
                        .HasDatabaseName("IDX_Notifications_IsRead");

                    b.HasIndex("NotificationType")
                        .HasDatabaseName("IDX_Notifications_NotificationType");

                    b.HasIndex("UserID")
                        .HasDatabaseName("IDX_Notifications_UserID");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentGateway")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("TransactionID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("PaymentID");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("IDX_Payments_CompanyID");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IDX_Payments_CreatedAt");

                    b.HasIndex("ProjectID")
                        .HasDatabaseName("IDX_Payments_ProjectID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_Payments_Status");

                    b.HasIndex("StudentID")
                        .HasDatabaseName("IDX_Payments_StudentID");

                    b.HasIndex("TransactionID")
                        .HasDatabaseName("IDX_Payments_TransactionID");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<int>("ApplicationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxApplicants")
                        .HasColumnType("int");

                    b.Property<string>("MinAcademicYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequiredSkills")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProjectID");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("IDX_Projects_CompanyID");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("IDX_Projects_Deadline");

                    b.HasIndex("IsVisible")
                        .HasDatabaseName("IDX_Projects_IsVisible");

                    b.HasIndex("ProjectCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Projects_ProjectCode")
                        .HasFilter("[ProjectCode] IS NOT NULL");

                    b.HasIndex("ProjectType")
                        .HasDatabaseName("IDX_Projects_ProjectType");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_Projects_Status");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.ProjectGroup", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("GroupID");

                    b.HasIndex("ProjectID")
                        .HasDatabaseName("IDX_ProjectGroups_ProjectID");

                    b.ToTable("ProjectGroups", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.ProjectModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EstimatedDuration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectModules", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.ProjectRequiredSkill", b =>
                {
                    b.Property<int>("ProjectSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectSkillID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.HasKey("ProjectSkillID");

                    b.HasIndex("ProjectID")
                        .HasDatabaseName("IDX_ProjectSkills_ProjectID");

                    b.HasIndex("SkillID")
                        .HasDatabaseName("IDX_ProjectSkills_SkillID");

                    b.HasIndex("ProjectID", "SkillID")
                        .IsUnique()
                        .HasDatabaseName("UQ_ProjectSkills_ProjectID_SkillID");

                    b.ToTable("ProjectRequiredSkills", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SkillCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillID");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IDX_Skills_IsActive");

                    b.HasIndex("SkillCategory")
                        .HasDatabaseName("IDX_Skills_SkillCategory");

                    b.HasIndex("SkillName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Skills_SkillName");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            SkillID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "Backend",
                            SkillName = "Backend"
                        },
                        new
                        {
                            SkillID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "Frontend",
                            SkillName = "Frontend"
                        },
                        new
                        {
                            SkillID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "UIUX",
                            SkillName = "UI&UX"
                        },
                        new
                        {
                            SkillID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "Mobile",
                            SkillName = "Mobile App"
                        },
                        new
                        {
                            SkillID = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "Frontend",
                            SkillName = "Web Development"
                        },
                        new
                        {
                            SkillID = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "AIML",
                            SkillName = "AI"
                        },
                        new
                        {
                            SkillID = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "Data",
                            SkillName = "Big Data"
                        },
                        new
                        {
                            SkillID = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "Testing",
                            SkillName = "Testing"
                        },
                        new
                        {
                            SkillID = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "Marketing",
                            SkillName = "Marketing"
                        },
                        new
                        {
                            SkillID = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "Marketing",
                            SkillName = "Social Media"
                        },
                        new
                        {
                            SkillID = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "Design",
                            SkillName = "Photoshop"
                        },
                        new
                        {
                            SkillID = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "Security",
                            SkillName = "Cybersecurity"
                        },
                        new
                        {
                            SkillID = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SkillCategory = "Mobile",
                            SkillName = "Flutter"
                        });
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Egypt");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProfileCompleteness")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("StudentIDNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UniversityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.HasIndex("AverageRating")
                        .HasDatabaseName("IDX_Students_AverageRating");

                    b.HasIndex("DepartmentID")
                        .HasDatabaseName("IDX_Students_DepartmentID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_Students_Status");

                    b.HasIndex("UniversityID")
                        .HasDatabaseName("IDX_Students_UniversityID");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasDatabaseName("IDX_Students_UserID");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.StudentReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("AreasForImprovement")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("CommunicationRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int?>("CompletedOpportunityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("ProblemSolvingRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("ProfessionalismRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ReviewTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Strengths")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StudentRespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("TeamworkRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("TechnicalSkillsRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("TimeManagementRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WouldHireAgain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("ReviewID");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("IDX_StudentReviews_CompanyID");

                    b.HasIndex("CompletedOpportunityID")
                        .IsUnique()
                        .HasDatabaseName("IDX_StudentReviews_CompletedOpportunityID")
                        .HasFilter("[CompletedOpportunityID] IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IDX_StudentReviews_CreatedAt");

                    b.HasIndex("Rating")
                        .HasDatabaseName("IDX_StudentReviews_Rating");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_StudentReviews_Status");

                    b.HasIndex("StudentID")
                        .HasDatabaseName("IDX_StudentReviews_StudentID");

                    b.HasIndex("CompanyID", "CompletedOpportunityID")
                        .IsUnique()
                        .HasDatabaseName("UQ_StudentReviews_CompanyID_CompletedOpportunityID")
                        .HasFilter("[CompletedOpportunityID] IS NOT NULL");

                    b.ToTable("StudentReviews", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.StudentSkill", b =>
                {
                    b.Property<int>("StudentSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentSkillID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ProficiencyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("StudentSkillID");

                    b.HasIndex("SkillID")
                        .HasDatabaseName("IDX_StudentSkills_SkillID");

                    b.HasIndex("StudentID")
                        .HasDatabaseName("IDX_StudentSkills_StudentID");

                    b.HasIndex("StudentID", "SkillID")
                        .IsUnique()
                        .HasDatabaseName("UQ_StudentSkills_StudentID_SkillID");

                    b.ToTable("StudentSkills", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.University", b =>
                {
                    b.Property<int>("UniversityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniversityID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("UniversityLogo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UniversityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UniversityID");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IDX_Universities_IsActive");

                    b.HasIndex("UserID")
                        .HasDatabaseName("IDX_Universities_UserID");

                    b.ToTable("Universities", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("VerificationCodeExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IDX_Users_Email");

                    b.HasIndex("UserType")
                        .HasDatabaseName("IDX_Users_UserType");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.UserSettings", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingID"));

                    b.Property<bool>("ApplicationNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("English");

                    b.Property<bool>("MessageNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ProfileVisibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Public");

                    b.Property<bool>("PushNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("UTC");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SettingID");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasDatabaseName("IDX_UserSettings_UserID");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Application", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Project", "Project")
                        .WithMany("Applications")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Company", "Company")
                        .WithMany("IssuedCertificates")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.Project", "Project")
                        .WithMany("Certificates")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.Student", "Student")
                        .WithMany("Certificates")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Company", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.User", "User")
                        .WithOne("Company")
                        .HasForeignKey("Sh8lny.Domain.Entities.Company", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.CompanyReview", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Company", "Company")
                        .WithMany("Reviews")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.CompletedOpportunity", "CompletedOpportunity")
                        .WithOne("CompanyReview")
                        .HasForeignKey("Sh8lny.Domain.Entities.CompanyReview", "CompletedOpportunityID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sh8lny.Domain.Entities.Student", "Student")
                        .WithMany("CompanyReviews")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CompletedOpportunity");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.CompletedOpportunity", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Application", "Application")
                        .WithOne("CompletedOpportunity")
                        .HasForeignKey("Sh8lny.Domain.Entities.CompletedOpportunity", "ApplicationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sh8lny.Domain.Entities.Certificate", "Certificate")
                        .WithOne("CompletedOpportunity")
                        .HasForeignKey("Sh8lny.Domain.Entities.CompletedOpportunity", "CertificateID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sh8lny.Domain.Entities.Project", "Project")
                        .WithMany("CompletedOpportunities")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.Student", "Student")
                        .WithMany("CompletedOpportunities")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.User", "Verifier")
                        .WithMany("VerifiedOpportunities")
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Application");

                    b.Navigation("Certificate");

                    b.Navigation("Project");

                    b.Navigation("Student");

                    b.Navigation("Verifier");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.ProjectGroup", "Group")
                        .WithMany("Conversations")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sh8lny.Domain.Entities.Project", "Project")
                        .WithMany("Conversations")
                        .HasForeignKey("ProjectID");

                    b.Navigation("Group");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.User", "User")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.DashboardMetric", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Company", null)
                        .WithMany("DashboardMetrics")
                        .HasForeignKey("CompanyID");

                    b.HasOne("Sh8lny.Domain.Entities.University", null)
                        .WithMany("DashboardMetrics")
                        .HasForeignKey("UniversityID");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Department", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.University", null)
                        .WithMany("Departments")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.ProjectGroup", "ProjectGroup")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.Student", "Student")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectGroup");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Message", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Company", "Company")
                        .WithMany("Payments")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sh8lny.Domain.Entities.Project", "Project")
                        .WithMany("Payments")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Project", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.ProjectGroup", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Project", "Project")
                        .WithMany("ProjectGroups")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.ProjectModule", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Project", "Project")
                        .WithMany("Modules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.ProjectRequiredSkill", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Project", "Project")
                        .WithMany("ProjectRequiredSkills")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.Skill", "Skill")
                        .WithMany("ProjectRequiredSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Student", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Sh8lny.Domain.Entities.University", "University")
                        .WithMany("Students")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Sh8lny.Domain.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Sh8lny.Domain.Entities.Student", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.StudentReview", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Company", "Company")
                        .WithMany("StudentReviews")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.CompletedOpportunity", "CompletedOpportunity")
                        .WithOne("StudentReview")
                        .HasForeignKey("Sh8lny.Domain.Entities.StudentReview", "CompletedOpportunityID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sh8lny.Domain.Entities.Student", "Student")
                        .WithMany("ReceivedReviews")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CompletedOpportunity");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.StudentSkill", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.Skill", "Skill")
                        .WithMany("StudentSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sh8lny.Domain.Entities.Student", "Student")
                        .WithMany("StudentSkills")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.University", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("Sh8lny.Domain.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("Sh8lny.Domain.Entities.UserSettings", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Application", b =>
                {
                    b.Navigation("CompletedOpportunity");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Certificate", b =>
                {
                    b.Navigation("CompletedOpportunity");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Company", b =>
                {
                    b.Navigation("DashboardMetrics");

                    b.Navigation("IssuedCertificates");

                    b.Navigation("Payments");

                    b.Navigation("Projects");

                    b.Navigation("Reviews");

                    b.Navigation("StudentReviews");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.CompletedOpportunity", b =>
                {
                    b.Navigation("CompanyReview");

                    b.Navigation("StudentReview");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Department", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Project", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Certificates");

                    b.Navigation("CompletedOpportunities");

                    b.Navigation("Conversations");

                    b.Navigation("Modules");

                    b.Navigation("Payments");

                    b.Navigation("ProjectGroups");

                    b.Navigation("ProjectRequiredSkills");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.ProjectGroup", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Skill", b =>
                {
                    b.Navigation("ProjectRequiredSkills");

                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.Student", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Certificates");

                    b.Navigation("CompanyReviews");

                    b.Navigation("CompletedOpportunities");

                    b.Navigation("GroupMemberships");

                    b.Navigation("Payments");

                    b.Navigation("ReceivedReviews");

                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.University", b =>
                {
                    b.Navigation("DashboardMetrics");

                    b.Navigation("Departments");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Sh8lny.Domain.Entities.User", b =>
                {
                    b.Navigation("Company");

                    b.Navigation("ConversationParticipants");

                    b.Navigation("Notifications");

                    b.Navigation("SentMessages");

                    b.Navigation("Settings");

                    b.Navigation("Student");

                    b.Navigation("VerifiedOpportunities");
                });
#pragma warning restore 612, 618
        }
    }
}
